# Generated by Django 4.0.4 on 2022-05-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='article title', max_length=20),
        ),
    ]
